# Generated by Django 5.2.17 on 2026-08-23 16:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bom", "0001_initial"),
        ("master_data", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("production_units", models.PositiveIntegerField()),
                ("production_unit", models.CharField(max_length=64)),
                ("receiving_department", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("RELEASED", "RELEASED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bom_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_releases",
                        to="bom.bomversion",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_production_releases",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_releases",
                        to="projects.project",
                    ),
                ),
                (
                    "released_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_production_releases",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_releases",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "production_release",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ProductionRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=200)),
                ("quantity_per_unit", models.DecimalField(decimal_places=6, max_digits=18)),
                ("required_quantity", models.DecimalField(decimal_places=6, max_digits=24)),
                ("procurement_required", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_requirements",
                        to="master_data.material",
                    ),
                ),
                (
                    "production_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="production.productionrelease",
                    ),
                ),
                (
                    "source_bom_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_requirements",
                        to="bom.bomline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_requirements",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_requirements",
                        to="master_data.unit",
                    ),
                ),
            ],
            options={
                "db_table": "production_requirement",
                "ordering": ("source_bom_line__source_row_number", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="productionrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("production_units__gt", 0)), name="ck_production_units_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "RELEASED", "CANCELLED"])),
                name="ck_production_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrequirement",
            constraint=models.UniqueConstraint(
                fields=("production_release", "source_bom_line"),
                name="uq_production_requirement_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_per_unit__gt", 0)),
                name="ck_requirement_unit_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_quantity__gt", 0)),
                name="ck_requirement_total_positive",
            ),
        ),
    ]
