# Generated by Django 5.2.17 on 2026-08-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0001_initial"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionrelease",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="productionrelease",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionrelease",
            name="cancelled_by_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_production_releases",
                to="tenancy.membership",
            ),
        ),
    ]
