# Generated by Django 5.2.17 on 2026-08-23 11:12

"""创建 tenant 与用户 membership 的首批租户边界。

迁移只建立企业和成员关系，不写入默认租户或管理员，避免部署时通过迁移
偷偷产生环境相关数据。现有数据库仅有 F-004 认证基础，无租户数据需要
回填。反向迁移会删除全部成员与租户，只适用于未承载真实数据的开发库。
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
                "db_table": "tenancy_tenant",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户成员",
                "verbose_name_plural": "租户成员",
                "db_table": "tenancy_membership",
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="ix_membership_user_active")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user"), name="uq_tenancy_membership_tenant_user"
                    )
                ],
            },
        ),
    ]
