# Generated by Django 5.2.17 on 2026-08-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(default="Asia/Shanghai", max_length=64),
        ),
    ]
