# Generated by Django 5.2.17 on 2026-08-24 15:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0001_initial"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="customer",
            name="bank_account",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="bank_routing_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="short_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_identifier",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("tax_identifier", models.CharField(blank=True, max_length=64)),
                ("bank_routing_number", models.CharField(blank=True, max_length=64)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("bank_account", models.CharField(blank=True, max_length=64)),
                ("service_description", models.CharField(blank=True, max_length=200)),
                ("english_name", models.CharField(blank=True, max_length=200)),
                ("english_address", models.CharField(blank=True, max_length=300)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "master_data_supplier",
                "ordering": ("code", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code"), name="uq_supplier_tenant_code"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "normalized_name"), name="uq_supplier_tenant_name"
                    ),
                ],
            },
        ),
    ]
