# Generated by Django 5.2.17 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0002_customer_address_customer_bank_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="part_attribute",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
