# Generated by Django 5.2.17 on 2026-08-26 13:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
        ("master_data", "0003_material_part_attribute"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDrawing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_format",
                    models.CharField(choices=[("PDF", "PDF"), ("DWG", "DWG")], max_length=8),
                ),
                ("version", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("revision_label", models.CharField(blank=True, max_length=64)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_drawing",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_material_drawings",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawings",
                        to="master_data.material",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_drawings",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "master_data_material_drawing",
                "ordering": ("material_id", "document_format", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("material", "document_format", "version"),
                        name="uq_drawing_material_format_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("material", "document_format"),
                        name="uq_drawing_material_format_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)), name="ck_drawing_version_positive"
                    ),
                ],
            },
        ),
    ]
