# Generated by Django 5.2.17 on 2026-08-23 16:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                ("device_model", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("planned_completion_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("ACTIVE", "ACTIVE"),
                            ("CLOSED", "CLOSED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="master_data.customer",
                    ),
                ),
                (
                    "owner_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "projects_project",
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "number"), name="uq_project_tenant_number"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["DRAFT", "ACTIVE", "CLOSED", "CANCELLED"])
                        ),
                        name="ck_project_status_valid",
                    ),
                ],
            },
        ),
    ]
