# Generated by Django 5.2.17 on 2026-08-23 12:40

"""建立租户级附件元数据和数据库/文件一致性状态。

二进制内容不会进入数据库，本迁移也不扫描或搬运旧文件。AVAILABLE 记录必须
同时具有大小和 SHA-256 摘要；反向迁移会删除元数据但不会删除存储目录中的文件，
因此只能在无真实附件的开发环境回滚，并应先运行附件对账。
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("display_filename", models.CharField(max_length=255)),
                ("detected_media_type", models.CharField(max_length=127)),
                ("detected_extension", models.CharField(blank=True, max_length=16)),
                ("size_bytes", models.PositiveBigIntegerField(null=True)),
                ("sha256_hex", models.CharField(max_length=64, null=True)),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                ("storage_backend", models.CharField(choices=[("local", "local")], max_length=16)),
                ("storage_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("available", "available"),
                            ("quarantined", "quarantined"),
                            ("failed", "failed"),
                            ("deleted", "deleted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "attachments_attachment",
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "created_at"],
                        name="ix_attachment_tenant_status",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "available"), _negated=True),
                            models.Q(("size_bytes__isnull", False), ("sha256_hex__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_attachment_available_integrity",
                    )
                ],
            },
        ),
    ]
