# Generated by Django 5.2.17 on 2026-08-23 16:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attachments", "0001_initial"),
        ("master_data", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("source_mapping", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("SUPERSEDED", "SUPERSEDED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_bom_versions",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_versions",
                        to="projects.project",
                    ),
                ),
                (
                    "published_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_bom_versions",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_bom_versions",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_versions",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "bom_version",
                "ordering": ("project_id", "version_number", "id"),
            },
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_row_number", models.PositiveIntegerField()),
                ("level_path", models.CharField(blank=True, max_length=100)),
                ("assembly_code", models.CharField(blank=True, max_length=100)),
                ("assembly_name", models.CharField(blank=True, max_length=200)),
                ("material_code", models.CharField(blank=True, max_length=64)),
                ("material_name", models.CharField(blank=True, max_length=200)),
                ("specification", models.CharField(blank=True, max_length=200)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "quantity_per_unit",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("unit_text", models.CharField(blank=True, max_length=64)),
                ("procurement_required", models.BooleanField(default=True)),
                ("remark", models.CharField(blank=True, max_length=500)),
                ("validation_errors", models.JSONField(default=list)),
                ("duplicate_key", models.CharField(blank=True, max_length=300)),
                ("duplicate_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="master_data.material",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="master_data.unit",
                    ),
                ),
                (
                    "bom_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="bom.bomversion",
                    ),
                ),
            ],
            options={
                "db_table": "bom_line",
                "ordering": ("source_row_number", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="bomversion",
            constraint=models.UniqueConstraint(
                fields=("project", "version_number"), name="uq_bom_project_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "PUBLISHED", "SUPERSEDED", "CANCELLED"])
                ),
                name="ck_bom_version_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.UniqueConstraint(
                fields=("bom_version", "source_row_number"), name="uq_bom_line_source_row"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_per_unit__isnull", True),
                    ("quantity_per_unit__gt", 0),
                    _connector="OR",
                ),
                name="ck_bom_line_quantity_positive",
            ),
        ),
    ]
