# Generated by Django 5.2.17 on 2026-08-23 11:31

"""建立租户级追加式审计记录表。

迁移不回填旧数据。ORM 会阻止正常应用路径更新或删除既有记录，但数据库管理员仍然
拥有底层维护能力，因此生产环境还需通过数据库账号权限、备份和监控共同保护证据。
反向迁移会永久删除审计记录，只能用于尚未承载真实审计数据的开发环境。
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("denied", "denied"),
                            ("failure", "failure"),
                        ],
                        max_length=16,
                    ),
                ),
                ("summary", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ("-occurred_at", "-id"),
            },
        ),
    ]
