# Generated by Django 5.2.17 on 2026-08-23 11:31

"""建立权限代码、角色模板、角色授权和成员角色表。

本迁移只建立可移植的数据结构，不写入默认矩阵数据。默认角色和权限将在 F-009
初始化流程中幂等写入，避免迁移历史承担可变的产品配置。反向迁移会删除授权配置，
只能用于尚未承载真实业务数据的开发环境。
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("code", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "authorization_permission",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("code", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "authorization_role",
            },
        ),
        migrations.CreateModel(
            name="MembershipRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_assignments",
                        to="authorization.role",
                    ),
                ),
            ],
            options={
                "db_table": "authorization_membership_role",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("membership", "role"), name="uq_authorization_membership_role"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("tenant", "tenant"), ("related", "related")], max_length=16
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="authorization.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to="authorization.role",
                    ),
                ),
            ],
            options={
                "db_table": "authorization_role_permission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "permission"), name="uq_authorization_role_permission"
                    )
                ],
            },
        ),
    ]
