# Generated by Django 5.2.17 on 2026-08-23 16:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequestLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=200)),
                ("requested_quantity", models.DecimalField(decimal_places=6, max_digits=24)),
                ("remark", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "procurement_purchase_request_line",
                "ordering": ("source_requirement_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("business_date", models.DateField()),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "procurement_purchase_request_sequence",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_number", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_purchase_requests",
                        to="tenancy.membership",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_request",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
