# Generated by Django 5.2.17 on 2026-08-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        ("procurement", "0001_initial"),
        ("production", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="production_release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requests",
                to="production.productionrelease",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requests",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="submitted_by_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_purchase_requests",
                to="tenancy.membership",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requests",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestline",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_request_lines",
                to="master_data.material",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestline",
            name="purchase_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="procurement.purchaserequest",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestline",
            name="source_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_request_lines",
                to="production.productionrequirement",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_request_lines",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestline",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_request_lines",
                to="master_data.unit",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequestsequence",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_request_sequences",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequest",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"), name="uq_request_tenant_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequest",
            constraint=models.UniqueConstraint(
                fields=("tenant", "request_number"), name="uq_request_tenant_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("tenant", "production_release"),
                name="uq_request_active_production",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "SUBMITTED", "CANCELLED"])),
                name="ck_request_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequestline",
            constraint=models.UniqueConstraint(
                fields=("purchase_request", "source_requirement"), name="uq_request_line_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequestline",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_quantity__gt", 0)),
                name="ck_request_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequestsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business_date"), name="uq_request_sequence_tenant_date"
            ),
        ),
    ]
