# Generated by Django 5.2.17 on 2026-08-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0002_initial"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="cancelled_by_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_purchase_requests",
                to="tenancy.membership",
            ),
        ),
    ]
