# Generated by Django 5.2.17 on 2026-08-25 12:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0003_material_part_attribute"),
        ("procurement", "0003_purchaserequest_cancelled_by_membership"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quote_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "CNY"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("JPY", "JPY"),
                            ("GBP", "GBP"),
                        ],
                        max_length=3,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=24)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                ("tax_included", models.BooleanField(default=True)),
                (
                    "minimum_order_quantity",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SUPPLIER", "SUPPLIER"),
                            ("HISTORICAL", "HISTORICAL"),
                            ("ERP", "ERP"),
                            ("MANUAL", "MANUAL"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=100)),
                ("remark", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("WITHDRAWN", "WITHDRAWN")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_supplier_quotes",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "request_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_quotes",
                        to="procurement.purchaserequestline",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="master_data.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_quotes",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "withdrawn_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawn_supplier_quotes",
                        to="tenancy.membership",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_supplier_quote",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SupplierDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=True)),
                ("supplier_code_snapshot", models.CharField(max_length=64)),
                ("supplier_name_snapshot", models.CharField(max_length=200)),
                ("currency", models.CharField(max_length=3)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=24)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                ("tax_included", models.BooleanField()),
                ("requested_quantity", models.DecimalField(decimal_places=6, max_digits=24)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_decisions",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "request_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_decisions",
                        to="procurement.purchaserequestline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_decisions",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_decisions",
                        to="procurement.supplierquote",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_supplier_decision",
                "ordering": ("request_line_id", "-version"),
            },
        ),
        migrations.AddConstraint(
            model_name="supplierquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gt", 0)), name="ck_supplier_quote_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 100)),
                name="ck_supplier_quote_tax_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierquote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_order_quantity__isnull", True),
                    ("minimum_order_quantity__gt", 0),
                    _connector="OR",
                ),
                name="ck_supplier_quote_minimum_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierdecision",
            constraint=models.UniqueConstraint(
                fields=("request_line", "version"), name="uq_supplier_decision_line_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierdecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("request_line",),
                name="uq_supplier_decision_line_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="ck_supplier_decision_version_positive"
            ),
        ),
    ]
