# Generated by Django 5.2.17 on 2026-08-25 14:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0003_material_part_attribute"),
        ("procurement", "0004_supplierquote_supplierdecision_and_more"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("supplier_code_snapshot", models.CharField(max_length=64)),
                ("supplier_name_snapshot", models.CharField(max_length=200)),
                ("currency", models.CharField(max_length=3)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "PURCHASE"),
                            ("OUTSOURCE", "OUTSOURCE"),
                            ("MIXED", "MIXED"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("ISSUED", "ISSUED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("order_number", models.CharField(blank=True, max_length=32, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_purchase_orders",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_purchase_orders",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "issued_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_purchase_orders",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="master_data.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("project_code_snapshot", models.CharField(max_length=64)),
                ("request_number_snapshot", models.CharField(max_length=32)),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=200)),
                ("part_attribute_snapshot", models.CharField(blank=True, max_length=32)),
                ("unit_name_snapshot", models.CharField(max_length=64)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=24)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=24)),
                ("tax_rate", models.DecimalField(decimal_places=4, max_digits=7)),
                ("tax_included", models.BooleanField()),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("remark_snapshot", models.CharField(blank=True, max_length=500)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="procurement.supplierdecision",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "request_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="procurement.purchaserequestline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order_line",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("business_date", models.DateField()),
                ("kind", models.CharField(max_length=16)),
                ("last_value", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_sequences",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order_sequence",
            },
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "order_number"), name="uq_order_tenant_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "ISSUED", "CANCELLED"])),
                name="ck_order_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["PURCHASE", "OUTSOURCE", "MIXED"])),
                name="ck_order_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("request_line",),
                name="uq_order_line_request_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="ck_order_line_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseordersequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "business_date", "kind"),
                name="uq_order_sequence_tenant_date_kind",
            ),
        ),
    ]
