# Generated by Django 5.2.17 on 2026-08-25 14:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
        ("procurement", "0005_purchaseorder_purchaseorderline_and_more"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_document",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_order_documents",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_documents",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order_document",
                "ordering": ("-version",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "version"), name="uq_order_document_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gt", 0)),
                        name="ck_order_document_version_positive",
                    ),
                ],
            },
        ),
    ]
