# Generated by Django 5.2.17 on 2026-08-26 13:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0001_initial"),
        ("master_data", "0004_materialdrawing"),
        ("procurement", "0006_purchaseorderdocument"),
        ("tenancy", "0002_tenant_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderDrawingPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("included_file_count", models.PositiveIntegerField()),
                ("missing_material_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_drawing_package",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_drawing_packages",
                        to="tenancy.membership",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawing_packages",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drawing_packages",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order_drawing_package",
                "ordering": ("-version",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderDrawingPackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=200)),
                ("document_format", models.CharField(max_length=8)),
                ("drawing_version", models.PositiveIntegerField()),
                ("revision_label", models.CharField(blank=True, max_length=64)),
                ("archive_path", models.CharField(max_length=500)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256_hex", models.CharField(max_length=64)),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_items",
                        to="master_data.materialdrawing",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="procurement.purchaseorderdrawingpackage",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order_drawing_package_item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderDrawingPackageMissing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=200)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missing_packages",
                        to="master_data.material",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="missing_materials",
                        to="procurement.purchaseorderdrawingpackage",
                    ),
                ),
            ],
            options={
                "db_table": "procurement_purchase_order_drawing_package_missing",
            },
        ),
        migrations.AddConstraint(
            model_name="purchaseorderdrawingpackage",
            constraint=models.UniqueConstraint(
                fields=("order", "version"), name="uq_order_drawing_package_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderdrawingpackage",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="ck_drawing_package_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderdrawingpackage",
            constraint=models.CheckConstraint(
                condition=models.Q(("included_file_count__gt", 0)),
                name="ck_drawing_package_included_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderdrawingpackageitem",
            constraint=models.UniqueConstraint(
                fields=("package", "drawing"), name="uq_drawing_package_item_drawing"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderdrawingpackagemissing",
            constraint=models.UniqueConstraint(
                fields=("package", "material"), name="uq_drawing_package_missing_material"
            ),
        ),
    ]
